New gst lead function done
Syntags-Co/indiacorporates-firebase-functions pull request #11
Opened 2021-05-10 12:00 UTC by AshishPis3

2021-05-10 13:40 UTC, ankitpise requested changes

2021-05-10 13:40 UTC, ankitpise commented on functions/src/leads/newleads.ts
> +            uri: 'https://crm.indiacorporates.com/Api//V8/module',
Use config variable for https://crm.indiacorporates.com

2021-05-10 13:40 UTC, ankitpise commented on functions/src/leads/newleads.ts
> +                res.send(body);
@mapuskar did you manage to hide unnecessary fields with the response?
@AshishPis3 what data from response we need for further operations exactly?

2021-05-10 13:40 UTC, ankitpise commented on functions/src/leads/newleads.ts
> +function leadDataValidator(body){
why this function is not in validator library? It seems like its validating the data

2021-05-10 13:40 UTC, ankitpise commented on functions/src/lib/validator.ts
> +    if (body.first_name === undefined || body.first_name.length < 4) {
@AshishPis3 checkout https://www.npmjs.com/package/parse-full-name library.

This returns proper data with salutation, firstname, middle name, last name etc.

If you find it useful use it.

2021-05-10 13:57 UTC, AshishPis3 commented on functions/src/leads/newleads.ts
> +                res.send(body);
Lead Id and other message ok

2021-05-10 14:03 UTC, AshishPis3 commented on functions/src/leads/newleads.ts
> +function leadDataValidator(body){
It will check lead type before calling specific lead type validation

2021-05-12 11:21 UTC, ankitpise approved these changes

2021-05-13 12:02 UTC, ankitpise approved these changes

2021-05-13 12:02 UTC, merged